<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Users\wwestlake\Documents\Visual Studio 2013\Projects\WritersWorkBench\WritersWorkBench.sln" total="2" errors="1" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2014-02-13" time="11:41:50">
  <environment nunit-version="2.6.3.13283" clr-version="2.0.50727.5477" os-version="Microsoft Windows NT 6.1.7601 Service Pack 1" platform="Win32NT" cwd="C:\Program Files (x86)\NUnit 2.6.3\bin" machine-name="WWESTLAKE-HP" user="wwestlake" user-domain="wwestlake-HP" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite type="Test Project" name="C:\Users\wwestlake\Documents\Visual Studio 2013\Projects\WritersWorkBench\WritersWorkBench.sln" executed="True" result="Failure" success="False" time="0.853" asserts="0">
    <results>
      <test-suite type="Assembly" name="C:\Users\wwestlake\Documents\Visual Studio 2013\Projects\WritersWorkBench\Tests\RepositoryTestSuite\bin\Debug\LagDaemon.WWB.RepositoryTestSuite.dll" executed="True" result="Failure" success="False" time="0.496" asserts="0">
        <results>
          <test-suite type="Namespace" name="LagDaemon" executed="True" result="Failure" success="False" time="0.477" asserts="0">
            <results>
              <test-suite type="Namespace" name="WWB" executed="True" result="Failure" success="False" time="0.477" asserts="0">
                <results>
                  <test-suite type="Namespace" name="RepositoryTestSuite" executed="True" result="Failure" success="False" time="0.477" asserts="0">
                    <results>
                      <test-suite type="TestFixture" name="RepositoryTests" executed="True" result="Failure" success="False" time="0.474" asserts="0">
                        <results>
                          <test-case name="LagDaemon.WWB.RepositoryTestSuite.RepositoryTests._1_RepositoryManager_CallsRepository_SavesProject" executed="True" result="Success" success="True" time="0.412" asserts="0" />
                          <test-case name="LagDaemon.WWB.RepositoryTestSuite.RepositoryTests._2_RepositoryManager_CallsReposiory_AllProjects" executed="True" result="Error" success="False" time="0.044" asserts="0">
                            <failure>
                              <message><![CDATA[System.InvalidOperationException : This action is invalid when the mock object is in verified state.]]></message>
                              <stack-trace><![CDATA[at Rhino.Mocks.Impl.VerifiedMockState.MethodCall(IInvocation invocation, MethodInfo method, Object[] args)
at Rhino.Mocks.Impl.Invocation.Actions.RegularInvocation.PerformAgainst(IInvocation invocation)
at Rhino.Mocks.Impl.RhinoInterceptor.Intercept(IInvocation invocation)
at Castle.Proxies.IRepositoryProxye7caef413810422cb745213303ea0fe6.IRepository.Query[T](Predicate`1 predicate)
at LagDaemon.WWB.Repository.ProjectManager.All() in c:\Users\wwestlake\Documents\Visual Studio 2013\Projects\WritersWorkBench\Repository\ProjectManager.cs:line 20
at LagDaemon.WWB.RepositoryTestSuite.RepositoryTests._2_RepositoryManager_CallsReposiory_AllProjects() in c:\Users\wwestlake\Documents\Visual Studio 2013\Projects\WritersWorkBench\Tests\RepositoryTestSuite\RepositoryTests.cs:line 57
]]></stack-trace>
                            </failure>
                          </test-case>
                        </results>
                      </test-suite>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>